service: ssrserverless-angular

plugins:
  - serverless-apigw-binary
  - serverless-offline
  - serverless-api-compression
  - serverless-associate-waf

frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 128
  timeout: 30
  stage: stg
  region: us-west-2

package:
  excludeDevDependencies: true
  exclude:
    - src/**
    - node_modules/**
    - e2e/**
    - coverage/**
    - .serverless/**
    - .angular/**
    - "!node_modules/aws-serverless-express/**"
    - "!node_modules/binary-case/**"
    - "!node_modules/type-is/**"
    - "!node_modules/media-typer/**"
    - "!node_modules/mime-types/**"
    - "!node_modules/mime-db/**"
    - '!node_modules/@vendia/**'
    - '!node_modules/@codegenie/**'

custom:
  apigwBinary:
    types:
      - "*/*"

functions:
  api:
    handler: lambda.ssrserverless
    events:
      - http: ANY /{proxy+}
      - http: ANY /
